FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

COPY target/personal-website-backend-1.0.0.jar app.jar

# Expose the port your application listens on
EXPOSE 8080

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]