#Use an official OpenJDK base image
FROM openjdk:17-jdk-slim as builder

#Set the working directory inside the container
WORKDIR /app

#Copy the pom.xml and download the project dependencies (if needed)
COPY pom.xml .
RUN mvn dependency:go-offline

#Copy the entire source code into the container
COPY src ./src

#Build the project
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

COPY target/personal-website-backend-1.0.0.jar app.jar

# Expose the port your application listens on
EXPOSE 8080

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]